#pragma once

/*
 * ============================================================================
 * File: SAMD21_Pinmap.h
 * Project: Grad Cap Display Hardware Definitions
 * Target MCU: SAMD21 companion/master board
 *
 * Description
 * -----------
 * This header defines the SAMD21 board-level pin assignments used by the master
 * controller hardware.
 *
 * Purpose
 * -------
 * - Centralize all board-level pin definitions for the SAMD21 companion board
 * - Provide a single source of truth for SPI, RS-485, SD-card routing, button,
 *   frame-sync, backlight PWM, and NeoPixel connections
 * - Keep GPIO assignments separate from higher-level driver and protocol code
 *
 * Naming convention
 * -----------------
 * - All pin symbols in this file begin with SAMD21_ to make it immediately
 *   clear that they are board-local hardware definitions for the SAMD21 board.
 * - Pin definitions use static constexpr int so they remain compile-time
 *   constants while also benefiting from C++ type checking and scoping.
 * - This file defines constants only. It does not declare functions.
 *
 * Source note
 * -----------
 * These assignments are derived from the earlier SAMD21_pinmap.h file and
 * renamed into the new naming convention.
 * ============================================================================
 */

// -----------------------------------------------------------------------------
// Shared SPI Bus
// -----------------------------------------------------------------------------

/* SPI MOSI line used by the SAMD21. */
static constexpr int SAMD21_PIN_SPI_MOSI = A10;

/* SPI MISO line used by the SAMD21. */
static constexpr int SAMD21_PIN_SPI_MISO = A9;

/* SPI clock line used by the SAMD21. */
static constexpr int SAMD21_PIN_SPI_SCK = A8;

// -----------------------------------------------------------------------------
// RS-485 Bus Interface
// -----------------------------------------------------------------------------

/* UART RX pin receiving data from the RS-485 transceiver. */
static constexpr int SAMD21_PIN_RS485_RX = A7;

/* UART TX pin driving data into the RS-485 transceiver. */
static constexpr int SAMD21_PIN_RS485_TX = A6;

/*
 * RS-485 driver-enable control pin.
 *
 * Current hardware convention:
 * - LOW  = receive mode
 * - HIGH = transmit mode
 */
static constexpr int SAMD21_PIN_RS485_DE = 4;

// -----------------------------------------------------------------------------
// Display / System Control Outputs
// -----------------------------------------------------------------------------

/* PWM output used for backlight control. */
static constexpr int SAMD21_PIN_BACKLIGHT_PWM = 5;

/* Frame-sync output generated by the SAMD21. */
static constexpr int SAMD21_PIN_FRAME_SYNC_OUT = A2;

// -----------------------------------------------------------------------------
// User Input / Status Peripherals
// -----------------------------------------------------------------------------

/* Pushbutton or user-sense input. */
static constexpr int SAMD21_PIN_BUTTON_SENSE = A3;

/* NeoPixel data output. */
static constexpr int SAMD21_PIN_NEOPIXEL_DATA = 11;

/* NeoPixel power-control pin. */
static constexpr int SAMD21_PIN_NEOPIXEL_POWER = 12;

// -----------------------------------------------------------------------------
// Shared micro SD Routing / Control
// -----------------------------------------------------------------------------

/* Chip-select signal driven by the SAMD21 toward the shared micro SD path. */
static constexpr int SAMD21_PIN_SD_CS = A1;

/*
 * Control signal used to connect or isolate the SAMD21 from the shared micro SD
 * SPI path.
 */
static constexpr int SAMD21_PIN_SD_BUS_CONNECT = A0;
